require("pixi.js");
require("pixi-particles");

const Support = require("./support/support.js");
const Interactivity = require("./interactivity/interactivity.js");
const RenderingSystem = require("./renderingSystem/renderingSystem.js");
const Graphic = require("./graphic/graphic.js");
const DisplayObject = require("./displayObject/displayObject.js");

module.exports = {
    Point: Support.Point,
    ObservablePoint: Support.ObservablePoint,
    Frame: Support.Frame,
    Matrix: Support.Matrix,
    Quad: Support.Quad,
    TransformBase: Support.TransformBase,
    Transform: Support.Transform,
    TransformStatic: Support.TransformStatic,
    GroupD8: Support.GroupD8,
    Setup: Support.Setup,
    Tools: Support.Tools,
    CanvasTinter: Support.CanvasTinter,
    Loader: Support.Loader,

    Ticker: Interactivity.Ticker,
    PixiEventListener: Interactivity.PixiEventListener,
    PixiPointerEventListener: Interactivity.PixiPointerEventListener,
    PixiMouseEventListener: Interactivity.PixiMouseEventListener,
    PixiTouchEventListener: Interactivity.PixiTouchEventListener,
    EventListener: Interactivity.EventListener,
    Event: Interactivity.Event,

    CanvasElement: RenderingSystem.CanvasElement,
    Configuration: RenderingSystem.Configuration,
    WebGLConfiguration: RenderingSystem.WebGLConfiguration,
    Settings: RenderingSystem.Settings,
    WebGLRenderTarget: RenderingSystem.WebGLRenderTarget,
    ContainerRenderer: RenderingSystem.ContainerRenderer,
    WebGLEnvironment: RenderingSystem.WebGLEnvironment,
    CanvasEnvironment: RenderingSystem.CanvasEnvironment,
    System: RenderingSystem.System,

    Shader: Graphic.Shader,
    GLSLShader: Graphic.GLSLShader,
    LookMaskShader: Graphic.LookMaskShader,
    AbstractShaderFactory: Graphic.AbstractShaderFactory,
    ShaderFactory: Graphic.ShaderFactory,
    Texture: Graphic.Texture,
    ImageTexture: Graphic.ImageTexture,
    RenderTexture: Graphic.RenderTexture,
    VideoTexture: Graphic.VideoTexture,
    AbstractTextureFactory: Graphic.AbstractTextureFactory,
    TextureFactory: Graphic.TextureFactory,
    TextStyle: Graphic.TextStyle,
    Look: Graphic.Look,

    Bounds: DisplayObject.Bounds,
    Container: DisplayObject.Container,
    Sprite: DisplayObject.Sprite,
    AnimatedSprite: DisplayObject.AnimatedSprite,
    SimpleText: DisplayObject.SimpleText,
    TilingSprite: DisplayObject.TilingSprite,
    BitmapText: DisplayObject.BitmapText,
    Mesh: DisplayObject.Mesh,
    Rope: DisplayObject.Rope,
    Plane: DisplayObject.Plane,
    NineSlicePlane: DisplayObject.NineSlicePlane,
    Shape: DisplayObject.Shape,
    Circle: DisplayObject.Circle,
    Ellipse: DisplayObject.Ellipse,
    Rectangle: DisplayObject.Rectangle,
    RoundedRectangle: DisplayObject.RoundedRectangle,
    Polygon: DisplayObject.Polygon,
    ShapeData: DisplayObject.ShapeData,
    AbstractContainerFactory: DisplayObject.AbstractContainerFactory,
    TextFactory: DisplayObject.TextFactory,
    BitmapTextFactory: DisplayObject.BitmapTextFactory,
    MeshFactory: DisplayObject.MeshFactory,
    ShapeFactory: DisplayObject.ShapeFactory,
    SpecialSpriteFactory: DisplayObject.SpecialSpriteFactory,
    Object2D: DisplayObject.Object2D,
    Particle: DisplayObject.Particle,
    Emitter: DisplayObject.Emitter,
    PathParticle: DisplayObject.PathParticle,
    AnimatedParticle: DisplayObject.AnimatedParticle,
};